---
name: Release on Launchpad

# on:
#   release:
#     types: [published]
on: [push]

env:
  LANG: "pl_PL.UTF-8"

jobs:
  build:
    name: Submit a build for Launchpad
    runs-on: ubuntu-latest
    container:
      image: elementary/docker:stable

    steps:
      - name: Set pl_PL.UTF-8
        run: |
            locale-gen pl_PL.UTF-8
            update-locale LANG=pl_PL.UTF-8

      - name: Install GPG Agent
        run: apt update && apt install -y gpg-agent
        
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        
      - name: Check out source code
        uses: actions/checkout@v1
        with:
          submodules: true

      # - name: Check changelog for bumped version
      #   run: |
      #     grep -q ${{ github.event.release.tag_name }} debian/changelog || { echo "Version not bumped!" && exit 1; }

      - name: Install build dependencies
        run: |
          apt update
          apt install -y devscripts dput
          apt install -y libgala-dev libgee-0.8-dev libglib2.0-dev libgranite-dev libgtk-3-dev libhandy-1-dev libxnvctrl0 libxnvctrl-dev
          apt install -y libdbus-glib-1-dev libwnck-3-dev libgtop2-dev libwingpanel-3.0-dev appstream debhelper libudisks2-dev
          apt install -y meson valac sassc git

      - name: Build the package
        run: debuild --no-lintian -S

      - name: Send to Launchpad
        run: |
          dput ppa:stsdc/monitor ../*_source.changes
