---
name: Launchpad release

# on:
#   push:
#       tags:
#         - '*'
on: [push, pull_request]

jobs:
  build:
    name: Submit a build for Launchpad
    runs-on: ubuntu-latest
    container:
      image: elementary/docker:unstable

    steps:
      - name: Check out proper version of sources
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
           gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
           passphrase: ${{ secrets.GPG_PASSPHRASE }}
      # - name: Check changelog for bumped version
      #   run: |
      #     grep -q ${{ github.event.release.tag_name }} debian/changelog || { echo "Version not bumped!" && exit 1; }
      - name: Install build dependencies
        run: |
          apt update
          apt install -y devscripts dput
          apt install -y libgala-dev libgee-0.8-dev libglib2.0-dev libgranite-dev libgtk-3-dev libhandy-1-dev
          apt install -y libdbus-glib-1-dev libwnck-3-dev libgtop2-dev libwingpanel-3.0-dev appstream debhelper
          apt install -y meson valac sassc git

      - name: Build the package
        run: debuild -S --no-lintian


      - name: Send to Launchpad
        run: |
          dput ppa:stsdc/monitor ../*_source.changes